### ISSUE TITLE
Version scheme

### ISSUE THREAD

**Issue by llrs** [tidyverse/style#103]
I think that the actual approach is to use `usethis::use_version` for version numbers in `x.y.z`. But there are some package which follow the `x.y.z.9000` style (like sessionInfo). 

Perhaps this is tied to the release cycle of each package, which also seem inconsistent, or how many users install from CRAN, a formal release, and how many from Github. 

Maybe a new section under Documentation might be worth ?

**Comment by hadley** [comment]
See http://r-pkgs.had.co.nz/description.html#version. I don't think this is a style issue (its more important)
