### ISSUE TITLE
@seealso in documentation

### ISSUE THREAD

**Issue by jennybc** [tidyverse/style#104]
Let's recommend how to write `@seealso`s.

I dither over continuing the sentence "**See also** ... this_cool_thing for more info. Another_cool_thing does something else related." and writing individually self-contained sentences like so:

<img width="664" alt="screen shot 2018-10-21 at 9 42 03 am" src="https://user-images.githubusercontent.com/599454/47301754-7f47e000-d5d4-11e8-832a-0fb6c4644fc9.png">

Perhaps it depends on whether you are just listing functions, writing one sentence, writing several sentences?

**Comment by krlmlr** [comment]
Maybe a `\description{}` would be easier to parse/scan if we're listing individual functions?

Manual see-alsos should be in harmony with the automatically created ones from `@family` too.

**Comment by hadley** [comment]
Given that `@seealso` contents forms a section, I recommended a bulleted list for multiple functions.
