### ISSUE TITLE
How to format class names: code or not?

### ISSUE THREAD

**Issue by jennybc** [tidyverse/style#105]
Let's decide which of these we want:

Option A: class names ARE NOT formatted as code:

> A tibble will have class tbl_df ...
> The `data.frame()` function returns an object of class data.frame ...
> `frame_matrix()` allows you to create a matrix by laying the data out in rows ...
> `predict()` expects an lm or glm object as input ...

Option B: class names ARE formatted as code:

> A tibble will have class `tbl_df` ...
> The `data.frame()` function returns an object of class `data.frame` ...
> `frame_matrix()` allows you to create a `matrix` by laying the data out in rows ...
> `predict()` expects an `lm` or `glm` object as input ...

Context: beefing up the roxygen2 docs around cross-linking help topics. Want to provide advice that covers our recommended treatment. So imagine all the classes in question (tbl_df, data.frame, matrix, lm, glm) are linked to the associated help topic.

https://github.com/klutometis/roxygen/pull/814

**Comment by hadley** [comment]
Per internal-tidyverse vote, we have agreed on option B.
