### ISSUE TITLE
long lines

### ISSUE THREAD

**Issue by Yeedle** [tidyverse/style#11]
[Long Lines](https://github.com/tidyverse/style/blob/master/04-pipes.Rmd#long-lines):
```r
iris %>%
  group_by(Species) %>%
  summarise(
    Sepal.Length = mean(Sepal.Length),
    Sepal.Width = mean(Sepal.Width),
    Sepcies = n_distinct(Species)
  ) %>%
  select(Species)
```
compare to

```r
iris %>%
  group_by(Species) %>%
  summarise(Sepal.Length = mean(Sepal.Length),
            Sepal.Width = mean(Sepal.Width),
            Species = n_distinct(Species)) %>%
  select(Species)
```

Matter of opinion, but I was just wondering what are the merits of the first one, esp. given that the second one is consistent with how [long line function args](https://github.com/tidyverse/style/blob/master/03-functions.Rmd#long-lines) are usually written.

**Comment by hadley** [comment]
That's when creating a function, not when calling it. See https://github.com/tidyverse/style/blob/master/02-syntax.Rmd#long-lines

**Comment by Yeedle** [comment]
I see, didn't realize. I prefer the second one though (more "geometric")...
