### ISSUE TITLE
More detail on when comments are useful

### ISSUE THREAD

**Issue by DavisVaughan** [tidyverse/style#120]
Would it make sense for the style guide to have more detail on comments? It could expand on the fact that comments are useful to explain the "why", but code can often be rewritten to be self explanatory for the "what". It could give some examples, like moving a small chunk of a function to its own function and giving it a descriptive name to remove the need for a comment. https://style.tidyverse.org/syntax.html#comments

**Comment by hadley** [comment]
I think that’s probably out of scope for a style guide — the main thing is to lay out the basic principles so you can skim without getting to bogged down in the details.
