### ISSUE TITLE
Re-home "Organising your functions" content from r-pkgs

### ISSUE THREAD

**Issue by jennybc** [tidyverse/style#121]
The section "Organising your functions" from the "R code" chapter has been removed, in favour of the treatment of this topic here. However this doesn't seem fully fleshed out here yet. I'm pasting the removed text here, so it can be integrated.

---

## Organising your functions {#r-organising}

While you're free to arrange functions into files as you wish, the two extremes are bad: don't put all functions into one file and don't put each function into its own separate file. (It's OK if some files only contain one function, particularly if the function is large or has a lot of documentation.). File names should be meaningful and end in `.R`.

```{r, eval = FALSE}
# Good
fit_models.R
utility_functions.R

# Bad
foo.r
stuff.r
```

Pay attention to capitalization, since you, or some of your collaborators, might be using an operating system with a case-insensitive file system (e.g., Microsoft Windows or OS X). Avoid problems by never using filenames that differ only in capitalisation.

My rule of thumb is that if I can't remember the name of the file where a function lives, I need to either separate the functions into more files or give the file a better name. (Unfortunately you can't use subdirectories inside `R/`. The next best thing is to use a common prefix, e.g., `abc-*.R`.).

The arrangement of functions within files is less important if you master two important RStudio keyboard shortcuts that let you jump to the definition of a function:

*   Click a function name in code and press __F2__.

*   Press __Ctrl + .__ then start typing the name:

<img width="20%" alt="file-finder" src="https://user-images.githubusercontent.com/599454/52308154-7b588780-2951-11e9-866f-9b34e5350c8b.png">

After navigating to a function using one of these tools, you can go back to where you were by clicking the back arrow at the top-left of the editor

<img width="7%" alt="arrows" src="https://user-images.githubusercontent.com/599454/52308206-9b884680-2951-11e9-99f5-4dd850517f65.png">

or by pressing Ctrl/Cmd-F9.

**Comment by davidbaniadam** [comment]
This sentence is neither in the style guide or the new version of R packages. 
 "don’t put all functions into one file and don’t put each function into its own separate file. (It’s OK if some files only contain one function, particularly if the function is large or has a lot of documentation.)"

**Comment by salim-b** [comment]
> (...) the two extremes are bad: don't put all functions into one file and don't put each function into its own separate file.

It is immediately clear to me why the latter is not desirable. But could you elaborate a little on why you think the former is bad?

**Comment by jennybc** [comment]
The overall motivation for the advice in this section is to make it easier to put your fingers and eye balls on a function (and those related to it). At some point in package size and complexity, it's becomes pretty miserable to have all the functions in one file.

**Comment by salim-b** [comment]
> At some point in package size and complexity, it's becomes pretty miserable to have all the functions in one file.

And why exactly is this?

As I see it, splitting code into separate files cannot sufficiently reduce complexity (though add additional in the worst case). A good organization and structure of the code according to sensible functionality, responsibilty, etc. areas _inside a single file_ is at least as good as splitting code into separate files by the same principles. As long as navigation inside the file is easy – which it is using e.g. RStudio.

Using R Markdown as the _source's_ source format can provide [further convenience](https://gitlab.com/salim_b/r/pkgs/pkgpurl/#details) to writing code.

I think splitting a package's code into separate files on the other hand isn't a proper solution to the underlying problem (handle complexity). Or am I missing something?

**Comment by jennybc** [comment]
There's a limit to how much debating I'm willing to do here and we're swiftly approaching it. I think it's fine if people have different opinions than what's in the book.

One reason that I like having, say, utility functions in a separate file from some user-facing function is that it's easier to get both in front of my eyeballs and fingertips if they live in separate files.

**Comment by jennybc** [comment]
In any case, this section is re-appearing in R Package shortly, in revised form, and I've just re-realized this issue is on style.tidyverse.org, so in fact I believe we can close this.
