### ISSUE TITLE
Use load_all() in README

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/style#126]
Currently, rendering an off-the-shelf `README.Rmd` (with `usethis::use_readme_rmd()`) requires installing the package, because it's [loaded with `library()`](https://github.com/r-lib/usethis/blob/ed9ae179da53a53adebb2f6d02d63383619db8f2/inst/templates/package-README#L50). Suggesting to load it with `load_all()` in the setup chunk, but keep the (harmless) `library()` call for the readers to see.

Reference: https://github.com/tidyverse/blob/pull/11#discussion_r255504402.

**Comment by hadley** [comment]
Fixed with `devtools::build_readme()` (which installs the package into a temporary library)
