### ISSUE TITLE
Spacing around - and +

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidyverse/style#129]
There is a discrepancy regarding how spaces ought to be around - and +.

beginning of **2.2.3 Infix operators** states that

> Most infix operators (==, +, -, <-, etc.) should always be surrounded by spaces:

But then next line states

> There are a few exceptions, which should never be surrounded by spaces:
> The operators with high precedence: ::, :::, $, @, [, [[, ^, unary -, unary +, and :.

**Comment by hadley** [comment]
It's not an inconsistency, it's just a bit confusing — the parenthetical is talking about infix `-` and `+` not unary prefix `-` and `+`+

**Comment by EmilHvitfeldt** [comment]
I see it now! thank you!
