### ISSUE TITLE
library(): to quote or not to quote

### ISSUE THREAD

**Issue by lorenzwalthert** [tidyverse/style#132]
What is preferred in general? 

```r
library(tidyverse) 
```

or 

```r
library("tidyverse")
```
? I think it is not specified in this style guide. I prefer the latter because it is clearly unambiguous and feels more natural for packages that don't feature NSE. It came up in https://github.com/r-lib/styler/issues/495 so I thought we should first decide here before implementing any rule on that in styler.

**Comment by hadley** [comment]
Definitely `library(tidyverse)`. Using quotes suggests that `x <- "tidyverse"; library(x)` will work

**Comment by lorenzwalthert** [comment]
Ok, I see your point. So for r-lib/styler#495, do you suggest that styler turns the `package` argument into an unquoted string, e.g. `library("ggplot2", ...)` into `librar(ggplot2, ...)`? And leave everything else including `x <- "tidyverse"; library(x, character.only = TRUE)` as is? So should we add a rule like this?

When loading/attaching a package with `library()`, don't quote the package name:
```r
# Good
library(tidyverse)

# Bad 
library('tidyverse')
```
Using quotation marks is confusing because it can make the reader think `x <- "tidyverse"; library(x)` loads the tidyverse library, which is not the case. 

I think this would best fit before [paragraph 3.3](https://style.tidyverse.org/functions.html#return), which is the only paragraph discussing a specific function call - and even a much less common one.

**Comment by hadley** [comment]
I don't think styler should mess with individual function calls in this way, and I don't think it's worth adding to the style guide.

**Comment by lorenzwalthert** [comment]
Ok.
