### ISSUE TITLE
Official stance on `switch` fall-through?

### ISSUE THREAD

**Issue by MichaelChirico** [tidyverse/style#143]
I recently filed a pull request with `SparkR` in which I removed redundant options from some `switch` statements (e.g. `switch('a', a=, b=2)`):

https://github.com/apache/spark/pull/24885

It created a bit of a catch 22 with the Apache linter because:

 - `=,` is rejected: no space around an infix
 - `= ,` is rejected: space before a comma

To be clear I'm not sure whether Apache is using the tidyverse style guide.

Nevertheless I tried to find a reference for what the "proper" approach is here and found this style guide is silent on the point... my instinct says `switch` statements are themselves discouraged (or superseded by a `tidyverse` analogue), but in that case I expected to find an explicit discouragement and suggested workaround.

FWIW, I did a rough benchmark and found it 40% faster to leave RHS missing when appropriate:

https://github.com/apache/spark/pull/24885#discussion_r325521563

**Comment by hadley** [comment]
We use `switch()` with implicit fall through, styling as `= ,`, e.g.

```R
switch(x
  a = ,
  b = 1, 
  c = 2,
  stop("Unknown `x`", call. = FALSE)
)
```

**Comment by MichaelChirico** [comment]
OK... maybe something to file with `lintr` then?

```
writeLines('switch(x,
  a = ,
  b = 1,
  c = 2,
  stop("Unknown `x`", call. = FALSE)
)', tmp <- tempfile())
lintr::lint(tmp)
```

gives

```
tmp:2:7: style: Commas should never have a space before.
  a = ,
     ~^
````
