### ISSUE TITLE
Assignments in function calls

### ISSUE THREAD

**Issue by lorenzwalthert** [tidyverse/style#148]
I think we don't have it explicitly anywhere but I feel the convention is not to assign values within function calls, although it can make code shorter, in particular in if statements:

```r
if (nzchar(from_conda <- path_derive_from_conda()) < 1) {
  from_conda
}
```
The alternative here would be 
```r
from_conda <- path_derive_from_conda()
if (nzchar(from_conda) < 1) {
  from_conda
}
```

Note the similarities with the controversial [PEP572](https://www.python.org/dev/peps/pep-0572/) in Python. It can also be useful in scenarios like this:
``` r
f <- function() {
  cat("some message here")
  1
}

captured <- capture.output(x <- f())
# use x and captured later
```
I don't know how to write this without calling `f()` twice otherwise.

Do we need a rule for this in the style guide?

**Comment by hadley** [comment]
I think it's generally bad practice and best avoided.
