### ISSUE TITLE
Implicit type conversion in conditional statements

### ISSUE THREAD

**Issue by lorenzwalthert** [tidyverse/style#149]
I don't think we have a rule but by convention, implicit conversion in if statements should probably be discouraged by the style guide:
```r
x <- 1:4
if (length(x)) {
  # do something
}
```

Instead, the condition should always evaluate to a logical I believe. 

```r
x <- 1:4
if (length(x) > 0) {
  # do something
}
```

Should such a rule be added?

**Comment by hadley** [comment]
Agreed
