### ISSUE TITLE
Proposal: Don't use & or | in if (should be && and ||)

### ISSUE THREAD

**Issue by MichaelChirico** [tidyverse/style#159]
Statements like

```
if (x & y) ...
```

Are prone to error when `length(x)>1` or `length(y)>1` (the mistaken case can be caught with the recent R environment variable `_R_CHECK_LENGTH_1_LOGIC2_`).

It's also less efficient to use `&` when `&&` is appropriate.

The same applies to `||` and `while`.

Vector versions can apply within the condition statement, inside an aggregator:

```
if (x && any(y | z))
```

**Comment by hadley** [comment]
Yeah, agreed, although this to me almost isn't style, but correctness. 

Probably also worth mentioning the related mistake of writing `x <- ifelse(scalar_cond, true, false)` instead of `x <- if (scalar_cond) true else false`.

**Comment by MichaelChirico** [comment]
We see the `ifelse` thing a lot. In fact we get a fair amount of usage of `ifelse1` which is basically a wrapper to allow that in functional form without the `ifelse()` overhead: `x <- ifelse1(scalar_cond, true, false)`, e.g. https://cran.r-project.org/web/packages/splus2R/splus2R.pdf

**Comment by MichaelChirico** [comment]
agreed it's a can of worms. fine to leave that be for now.
