### ISSUE TITLE
apply markdown style guide for prose

### ISSUE THREAD

**Issue by maxheld83** [tidyverse/style#161]
I'd love some standardisation of how to style markdown in the context of R projects, and packages especially.

Markdown style is orthogonal to styling R, so this may be considered out of scope.
Howeber, I'd suggest that because almost every R project uses markdown in some pretty integral places, some norm for the community might still be helpful.

In decreasing order of applicability, markdown should be styled accordingly in:

1. `*.Rmd` such as in vignettes
2. Roxygen comments, when using markdown syntax.
3. Other comments (only a small subset would apply)

With markdown styling being somewhat orthogonal to rstats, it might be appropriate to just reuse existing style guides, formatters and linters, including:

- [Google](https://github.com/google/styleguide/blob/gh-pages/docguide/style.md)
- [Bitbucket](https://confluence.atlassian.com/bitbucketserver/markdown-syntax-guide-776639995.html)
- [GitLab](https://about.gitlab.com/handbook/markdown-guide/)

*If* there is some interest in standardising on / referring to a markdown style guide inside tidyverse/style, I see these TODOs:

- [ ] choose one of the markdown style guides
- [ ] adapt the style guide where necessary (for example, how to deal with line length https://github.com/tidyverse/style/issues/162)
- [ ] point to / explain rationale for markdown style guide
- [ ] make the source of this repo compliant (to set a good example).
- [ ] choose a recommended linter
- [ ] choose a recommended formatter
- [ ] wrap linter and/or formatter in R package or functions so they can be used conveniently in existing community toolchains.

I'd be happy to draft a PR on this, though I'd need some guidance on which of the existing style guides is most appropriate for the tidyverse community.

**Comment by hadley** [comment]
For us, I think this is now mostly superseded by the visual editor — we just recommend whatever the visual editor defaults are. (With the possible exception of text wrapping, because I think "sentence" wrapping is so much better for git.)
