### ISSUE TITLE
Keyword arguments -- to quote or not to quote

### ISSUE THREAD

**Issue by MichaelChirico** [tidyverse/style#163]
We recently started enforcing a rule that named arguments should only be quoted when required, e.g.

```
# bad
c("a" = 1, "b" = 2, "an elephant" = 3)

# good
c(a = 1, b = 2, "an elephant" = 3)
```

However, some small pushback we got referenced some tidyverse manuals, e.g.:

 - https://www.rdocumentation.org/packages/plyr/versions/1.8.6/topics/rename uses `rename(mtcars, c("disp" = "displacement"))`
 - https://dplyr.tidyverse.org/reference/join.html uses `band_members %>% full_join(band_instruments2, by = c("name" = "artist"))`

R cannot tell the difference between the two:

```
identical(
  parse(text = 'c(a = "b")', keep.source = FALSE),
  parse(text = 'c("a" = "b")', keep.source = FALSE)
)
# [1] TRUE
```

But given the examples in the documentation, I am wondering whether this is an unwritten rule, and if so, could we explicate it (it only applies to joins? renames?)

**Comment by lorenzwalthert** [comment]
I don't think they should be treated differently within R as they are parsed to the same expression. And I wouldn't know how you want to distinguish given the parser can't distinguish. Quoting on the command line is probably a different story, e.g if a
`--key=1` should be treated the same or not as `--key="1"`.

**Comment by MichaelChirico** [comment]
FWIW the parser also can't distinguish single from double quotes, by
tidyverse style still weighs in:

https://style.tidyverse.org/syntax.html#data

And also to clarify slightly, it IS possible to tell the difference, c.f.

utils::getParseData(parse(text = "foo('a' = 1, b = 2)"))

but only when keep.source=TRUE

**Comment by hadley** [comment]
I don't think I have a strong opinion either way — I think it depends a bit on the situation. If you want to emphasise symmetry you use quotes; if you want to make the left hand side look different to the right, don't use quotes. I think I'd usually use quotes in the `by` argument to joins because it's variable names on both sides, but I'd never use them in `mutate()` because the lhs is a variable name and the rhs is an expression.

**Comment by MichaelChirico** [comment]
Thanks... in fact our rule started from `data.frame()` and grew from there... I do think it's nice to distinguish LHS from RHS variables in `by`, but I also don't feel very strongly there.

It seems hard to come up with a good rule worthy of writing "in stone", so I'll close.
