### ISSUE TITLE
Sections 2.5 and 3.2 are somewhat contradictory

### ISSUE THREAD

**Issue by MichaelChirico** [tidyverse/style#164]
From [2.5](https://style.tidyverse.org/syntax.html#long-lines)

> If a function call is too long to fit on a single line, use one line each for the function name, each argument, and the closing `)`. This makes the code easier to read and to change later.

```
# Good
do_something_very_complicated(
  something = "that",
  requires = many,
  arguments = "some of which may be long"
)

# Bad
do_something_very_complicated("that", requires, many, arguments,
                              "some of which may be long"
                              )
```

The `# Bad` example looks a lot like the recommended syntax for long function definitions;

From [3.2](https://style.tidyverse.org/functions.html#long-lines-1)

> If a function definition runs over multiple lines, indent the second line to where the definition starts.

```
# Good
long_function_name <- function(a = "a long argument",
                               b = "another argument",
                               c = "another long argument") {
  # As usual code is indented by two spaces.
}

# Bad
long_function_name <- function(a = "a long argument",
  b = "another argument",
  c = "another long argument") {
  # Here it's hard to spot where the definition ends and the
  # code begins
}
```

I don't think the two recommendations are fundamentally inconsistent, but it would be useful to call out the case of function definitions in 2.5 and/or link to 3.2 from there.

**Comment by hadley** [comment]
I think this is now mostly superseded by #173.
