### ISSUE TITLE
(How) should options be documented?

### ISSUE THREAD

**Issue by lorenzwalthert** [tidyverse/style#165]
I wonder how R options could be documented consistently and if it is worth specifying this in the style guide. For many tidyverse packages such as `{purrr}`, `{tibble}` or `{dplyr}`, I can't quickly find all options documented in one place, e.g. a vignette or help file. Ideally, there would be a consistent name for this, e.g. in `{styler}`, we could call the help file `styler_options` to avoid a helpfile name conflict with `?options`. In my opinion, options are part of the API and should be documented. Maybe this also fits better into r-pkgs, but since there is already a package development section here, I felt I'd open it here.

**Comment by krlmlr** [comment]
I like the way renv is doing this -- but they have `?renv::config` and `?renv::settings` . Should we settle on an overarching `?<package>::options` or perhaps `?<package>::package_options` ? The former would add a disambiguation page to `?options`, not sure if this is a good or a bad thing.

**Comment by luciorq** [comment]
It would indeed be beneficial to have a standard place to look for options in every package.

Name clashes with `base` _R_ functions are always controversial, it can become a pain point in the future.  Especially as several packages would adhere to having `<package>::options`.

Despite being too verbose, `?<package>::package_options` looks like a good compromise. Using `config` or `settings` is not as mnemonical as having an "options" term.

**Comment by krlmlr** [comment]
pillar now has a `pillar_options` help page: https://pillar.r-lib.org/dev/reference/pillar_options.html. The object underneath is not exported yet.

**Comment by hadley** [comment]
See also discussion in #111; we're working on a bigger write up which we'll seek comments on in the next couple of months.
