### ISSUE TITLE
Moving towards {package} for package naming

### ISSUE THREAD

**Issue by lorenzwalthert** [tidyverse/style#180]
The current recommendation is to use **package** on first usage, then just package I believe, or just package (Reference: https://github.com/tidyverse/style/issues/50). A recent trend is that people opt for {package}, .e.g. [on Twitter](https://twitter.com/search?q=%23rstats%20%7Bpurrr%7D&src=typed_query&f=top). This notation is deeply rooted in base R, e.g. in help files:

![Screenshot 2021-10-28 at 20 14 46](https://user-images.githubusercontent.com/10477073/139312228-a166c94d-d826-4490-9870-54947490ef2c.png)

To me, it makes perfect sense because it won't be confused with `code_we <- write` or `pkg::fun()`, yet {package} stands out from normal text with a unique visual signature, without conflicting with common usage of *italics*, **bold** or "quoted".

Here's a visual comparison:

* Thanks to {purrr} and {glue}, I can call myself now a *real* Data Scientist. I fell in love with `purrr::map()` **immediately**.
***
* Thanks to **purrr** and **glue**, I can call myself now a *real* Data Scientist. I fell in love with `purrr::map()` **immediately**.
***
* Thanks to purrr and glue, I can call myself now a *real* Data Scientist. I fell in love with `purrr::map()` **immediately**.

**Comment by kellijohnson-NOAA** [comment]
I would add the following suggestion to @lorenzwalthert's. If you delineate a package using the {packagename} convention, one should NOT put the work package after the curly braces. All of the suggestions provided by @lorenzwalthert follow this convention but I see lots of examples on the web that look like {packagename} package. I find it redundant and think it would be a good idea, if @lorenzwalthert's suggestion is included in the style guide, to explicitly state 
>The word package should not be added after the curly braces.

**Comment by IndrajeetPatil** [comment]
Using this convention also helps `{pkgdown}` to link to the package website, if one exists and is mentioned in the `DESCRIPTION` file:

``` r
downlit:::autolink_curly("{cli}")
#> [1] "<a href='https://cli.r-lib.org'>cli</a>"
```

<sup>Created on 2024-04-21 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
