### ISSUE TITLE
return() in pipes should go on its own line

### ISSUE THREAD

**Issue by MichaelChirico** [tidyverse/style#182]
This is closely related to the inline statements section:

https://style.tidyverse.org/syntax.html#inline-statements

> Function calls that affect control flow (like `return()`, `stop()` or `continue`) should always go in their own `{}` block

`return()` should never be inlined in a pipe:

```
x %>% foo() %>% bar() %>% return()
```

should always be

```
x %>%
  foo() %>%
  bar() %>%
  return()
```

Does this belong better in the cited section, or in the section on pipes (e.g. https://style.tidyverse.org/pipes.html#short-pipes)?

**Comment by hadley** [comment]
Hmmm, I'm not sure I'd ever put a `return()` in a pipe. I think control flow generally belongs outside of pipes.

**Comment by MichaelChirico** [comment]
of course it's kind of irrelevant post #188 -- `return()` inside `|>` is not allowed. so I'm happy to close this as moot
