### ISSUE TITLE
Recommendations for vertical whitespace

### ISSUE THREAD

**Issue by MichaelChirico** [tidyverse/style#185]
Currently, the guide is silent on any recommendations re: vertical whitespace. Google's C++ guide has several recommendations:

https://google.github.io/styleguide/cppguide.html#Vertical_Whitespace

Most of it is relevant to R; is it worthwhile to call out any rules here?

**Comment by hadley** [comment]
Yeah, I like that advice. 

One idea that I've been noodling on is "paragraphs" of code, i.e. you want to keep related thoughts together in one contiguous block, and then you when you start a new thought, you add a gap. But I don't know how to make the precise enough to be useful to other people.
