### ISSUE TITLE
Enforce variable desambiguation in style

### ISSUE THREAD

**Issue by jfouret** [tidyverse/style#196]
Hi, 

The name collision might cause mistakes when using pipes or some tidyverse functions.

In general, I would suggest the use of `.data` and `.env` to be added in style recommandation.

I would also suggest the use of `dplyr::across` and `tidyselect` for the `dplyr::group_by` or similar features.

Below are examples:

```R
################################################################################

library(magrittr)

alphabet<- tibble::tibble(
  rank= seq_len(26),
  letter= c("a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", 
    "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x","y", "z"),
  type = factor(c("v", "c", "c", "c", "v", "c", "c", "c", "v", "c", "c", "c",
    "c", "c", "v", "c", "c", "c", "c", "c", "v", "c", "c", "c", "v", "c"))
)

rank <- 5
letter = "type"

# BAD

# 1
dplyr::filter(alphapet, rank <= rank)

# 2
dplyr::group_by(alphabet, type) %>% dplyr::group_by(letter) %>% dplyr::count()


# GOOD

# 1
dplyr::filter(alphabet, .data$rank <= .env$rank)

# 2
dplyr::group_by(alphabet, type) %>%
  dplyr::group_by(
    dplyr::across(tidyselect::all_of(.env$letter)
  )
) %>%
  dplyr::count()

```

**Comment by hadley** [comment]
IMO variable name clashes are just not common enough to rise to the level of being included in this style guide. In other words, you should deal with them as they arise, not prospectively avoid the problem by always using `.env` and `.data`.
