### ISSUE TITLE
Column names in join calls - to include or not to include?

### ISSUE THREAD

**Issue by tvqt** [tidyverse/style#206]
I was answering a question on StackOverflow, and I got a comment from a more senior user saying that "it's a good habit to explicitly specify which columns are joined by". I thought I would check the style guide, and to my surprise, it had nothing to say about it (nor did any other R style guide I could find, for that matter).

In a circumstance such as:

```
df1 <- tibble(
    Country = c("France", "Spain", "England")
)

df2 <- tibble(
    Country = rep(c("France", "Spain", "England"), each = 2),
    League = c("Ligue 1", "Ligue 2", "Liga", "Liga 2", "PL1", "PL2")
)
```
You could join with a `by = "Country"`, or without one, it has the same result. 

I was wondering if this has come up before, or if not, if there is some kind of stance on it. Many thanks!

**Comment by hadley** [comment]
If you run that code:

``` r
library(dplyr, warn.conflicts = FALSE)

df1 <- tibble(
  Country = c("France", "Spain", "England")
)

df2 <- tibble(
  Country = rep(c("France", "Spain", "England"), each = 2),
  League = c("Ligue 1", "Ligue 2", "Liga", "Liga 2", "PL1", "PL2")
)

df3 <- df1 |> left_join(df2)
#> Joining with `by = join_by(Country)`
```

<sup>Created on 2024-08-09 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

You get a message, and that message is a hint that you should supply the argument. The general principle is that you should try and make your functions as quiet a possible, so any messages are a good sign that we think you should supply the argument.
