### ISSUE TITLE
extending the style guide for roxygen2 documentation

### ISSUE THREAD

**Issue by lorenzwalthert** [tidyverse/style#21]
I was wondering whether it would make sense to extend the style guide with regard to `roxygen2` documentation, i.e. by giving guidelines on `roxygen2`-specific topics like :

* capitalisation of first letter in argument descriptions / bullet lists etc.
* Using or not using periods at the end of argument descriptions / bullet lists etc.
* Indention when description corresponding to a roxygen tag spans over multiple lines. 
* The order in which roxygen tags should be used.
* When to use `code_style_font` (only for functions, for variables, function arguments, TRUE / FALSE, NA etc.)?
* Whether to use `function_call()` or `function_call` when referring to a function.
* the use of data.frame, data frame or dataframe and the like.

I note that some conventions seem to exist, but even then it would make sense to turn the implicit into the explicit.

**Comment by hadley** [comment]
Yes, definitely a good idea!

**Comment by hadley** [comment]
Any interest in getting something started with a PR? 

I'm sure @jennybc would also be interested and might chime in with suggestions

**Comment by lorenzwalthert** [comment]
Ok, cool. I can start to work on a PR. I suggest to create a new chapter then. I will have a look at the conventions used in recently created tidyverse packages such as `forcats`, `readxl` and maybe also `roxygen2`to deduce some consistent rule set with regard to the bullet points mentioned above. If @jennybc has suggestions, I am more than happy to consider those in the PR, I guess either as comments or as PR to my PR or whatever seems to be most convenient. 😊

**Comment by jennybc** [comment]
I am definitely happy to help. @lorenzwalthert maybe you should tag me or request review from me once you get the ball rolling and I can pitch in. I know some of the unwritten conventions and am eager to know or establish the rest.

**Comment by jennybc** [comment]
More fodder (*I might add to this as things cross my radar*):

  * Whenever possible HYPERLINK, don't just mention. Applies to anything that has a reasonable target. I'm mostly thinking about other R help pages. But linking out is also encouraged.
  * The use of templates wherever duplication and self-contradiction / self-inconsistency is a risk.
  * Prefer Markdown (?).

**Comment by hadley** [comment]
@jennybc I've mostly gone sour on templates, preferring the new include functionality.

And yes markdown is absolutely preferred, not least because it makes linking so much easier.

**Comment by jennybc** [comment]
I will have to educate myself about the include functionality! I didn't really know of it.

**Comment by lorenzwalthert** [comment]
@jennybc I just submitted PR #24, but unfortunately, I could not assign you. Please have a look if you want (and assign yourself?), I added a little PR description and some comments already. @hadley I am not sure about what you mean regarding "the new include functionality". If you are, as @jennybc said, referring to `@inherit`, I can update the PR to include `@inherit` and friends. It's also a question of scope, i.e. how narrow style is defined here.
Looking forward to your feedback.

I initially wanted to create an ordered list of all roxygen tags. But since there are so many and you usually just need a few, I was wondering whether it makes sense to really specify in what order they should be used. Please advise on that.

**Comment by lorenzwalthert** [comment]
I guess this is closed by #24 and #29.
