### ISSUE TITLE
Indents - is 2 spaces really good?

### ISSUE THREAD

**Issue by PD-LUHC** [tidyverse/style#219]
https://github.com/tidyverse/style/blob/fbdebd8858baf7a273ab6cd78237484ef03478cb/syntax.Rmd#L288C1-L289C49

Is there a reason why 2 space indents is considered good when the published [R coding standard recommends 4?](https://cran.r-project.org/doc/manuals/R-ints.html#R-coding-standards). 2 spaces would also seem to go against the convention of most other languages and accepted practices. Under normal settings 2 Spaces also goes against pretty well established indent conventions from the print industry (based on literally centuries worth of reading ergonomics learning). Basically it seems like there are number of good reasons to make recommended default indents 4 or more spaces rather than 2.

It might be nice to have a discussion about this as the default goes against conventional wisdom and can cause readability and accessibility issues. At the very least it might be nice to have a documented explanation as to why broader indent conventions are being diverged from in tidyverse.

**Comment by hadley** [comment]
Thanks for the thoughts, but we don't have any plans to reconsider the indent size at this time. This would be a big change that would instantly make just about every piece of code out of compliance with the style guide.

**Comment by PD-LUHC** [comment]
Thanks for taking the time to respond to what was a somewhat self-indulgent issue. I certainly appreciate the "this sub-optimal habit is too entrenched to do anything about" perspective - convention and inertia are definitely not trivial.

If there is a better mechanism by which this topic can be raised with the broader community then please advise. If not for any other reason, the point about accessibility, to my mind at least, makes it something worth broader discussion somewhere.
