### ISSUE TITLE
Mutate instead of sub assignment

### ISSUE THREAD

**Issue by lorenzwalthert** [tidyverse/style#25]
In a [PR](https://github.com/krlmlr/styler/pull/21) and a subsequent [issue](https://github.com/krlmlr/styler/issues/24) reviewed by @krlmlr, I was advised to avoid sub assignment when possible. I think I might be reasonable to extend the style guide in this regard, namely section 2.6.

```r
# Good
pd <- pd %>%
  indent_round(pd, indent_by = 2) %>%
  mutate(child = map(child, indent_round_nested)

# Bad
pd <- indent_round(pd, indent_by = 2)
pd$child <- map(pd$child, indent_round_nested)
```
What do you think?

**Comment by hadley** [comment]
I think it's too hard to say in general. Sometimes I'd favour the first, other times I'd favour the second.

**Comment by lorenzwalthert** [comment]
Ok.
