### ISSUE TITLE
Add a chapter on S3, S4 and R6

### ISSUE THREAD

**Issue by jonmcalder** [tidyverse/style#36]
Would you consider it within the scope of the `tidyverse` style guide to cover some of your suggestions and conventions regarding each of R's object oriented programming paradigms?

With your approval, I'd be happy to get this going with a PR based on some of the content from section 3 of Adv-R.

**Comment by hadley** [comment]
The chapter on S4 would be don't use it. I don't think R6 should be used sufficiently frequently to need a chapter. But a chapter on S3 would be good!

**Comment by jonmcalder** [comment]
I didn't envision covering a lot of content so actually meant one combined chapter for all 3 topics with a small section on each, but I see your point. Will submit a PR sometime in the next few days.

**Comment by hadley** [comment]
I think style should cover things like:

* camel case for class names
* when to use the package name as part of the class name

**Comment by hadley** [comment]
I think this is now mostly supplanted by http://adv-r.hadley.nz/s3.html etc
