### ISSUE TITLE
Clarify spacing around bang-bang operators

### ISSUE THREAD

**Issue by lorenzwalthert** [tidyverse/style#38]
I think it would be useful to add an example under section [2.2 Spacing](http://style.tidyverse.org/syntax.html#spacing) on how spacing should be done around `!!!` and `!!`. In the [programming with dyplr](http://dplyr.tidyverse.org/articles/programming.html) vignette, there is no spacing around those operators whereas there is spacing around them in the help file for `rlang::quasiquotation` (up-to-date package version 0.1.2.9000).
Reference: https://github.com/krlmlr/styler/pull/110.

**Comment by hadley** [comment]
The other important style is that `!!` and `!!!` should always be enclosed in parens when used with infix functions (i.e. you should never rely on the often surprising default precedence)

I don't have any strong feeling about spaces. @lionel- what do you prefer?

**Comment by lionel-** [comment]
I prefer a space to give a bit of room to those noisy operators.

**Comment by lorenzwalthert** [comment]
@lionel-  If the preceding token is a brace (which seems to be the case very often), would you write `call( !! xyz)` for example? At the end of [Section 2.2](http://style.tidyverse.org/syntax.html#spacing), it is stated that there should not be a space after `(`, so I think this new bang-bang rule would create an exception to that rule then.

**Comment by lionel-** [comment]
I would never write it like that ;)

**Comment by krlmlr** [comment]
@lionel-: Can you please confirm, to avoid confusion:

```r
# good
call(!! xyz)

# bad
call( !! xyz)
```

**Comment by lionel-** [comment]
confirmed 👍

**Comment by lorenzwalthert** [comment]
So should we add this example to section 2.2 then? I can do a PR.

**Comment by hadley** [comment]
Yes please!
