### ISSUE TITLE
Line breaks in function calls with named arguments

### ISSUE THREAD

**Issue by lorenzwalthert** [tidyverse/style#39]
In the [styler](https://github.com/krlmlr/rlang/pull/1#discussion_r134577124) project, we came across the question whether the rule to

>  break the line after `(` if a function call does not fit on one line

applies to all functions, or whether `switch()`, `ifelse()` and friends are an exception to it In other words, whether
```r
switch(on_same_line,
  next_line,
  another_new_line
)
```
Is preferred over
```r
switch(
  on_next_line,
  next_line,
  another_new_line
)
```

Another (potential) candidate is `case_when()`. 

Reference: https://github.com/krlmlr/rlang/pull/1#discussion_r134577124, https://github.com/krlmlr/styler/pull/152.

**Comment by hadley** [comment]
I don't think your example is quite right. I think the question has to involve named arguments.

```R
switch(on_same_line,
  option_a = next_line,
  option_b = another_new_line
)
```

And I think the principle is that it's ok to put all the un-named arguments on the first line, if they fit. If they don't fit on one line, then they should be spread over multiple lines. I think this convention is nice for `lapply()`/`map()`:

```R
map(x, f,
  extra_argument_a = 10,
  extra_argument_b = NA
)
```

If no arguments are named, and it doesn't fit on one line.then each argument always gets its own line.

**Comment by lorenzwalthert** [comment]
Ok, thanks for the clarification. cc: @krlmlr

**Comment by krlmlr** [comment]
Relevant links with a draft and another corner case:

- https://github.com/krlmlr/styler/issues/125#issuecomment-323018778
- https://github.com/krlmlr/styler/pull/149#discussion_r134669117

**Comment by lorenzwalthert** [comment]
To close this issue, can we include such a paragraph in the style guide that describes the principle outlined above? I can get us started with PR if @hadley does not want to do it himself.

**Comment by hadley** [comment]
The principle should mention something about unnamed arguments being special - you only omit the names of arguments when they are used sufficiently commonly (i.e. with almost every invocation of that function) that you can assume most readers will know know what they are.
