### ISSUE TITLE
Spacing  in function return example

### ISSUE THREAD

**Issue by erinhaswell** [tidyverse/style#44]
Seems like there is inconsistent spacing after `function(x, y)` within  the `# Good` example for [https://github.com/tidyverse/style/blob/master/03-functions.Rmd#return](url)

```
# Good
find_abs <- function(x, y){
  if (x > 0) return(x)
  x * -1
}
add_two <- function(x, y) {
  x + y
}
```

Should `find_abs <- function(x, y){` be replaced with `find_abs <- function(x, y) {`?

**Comment by hadley** [comment]
Thanks! If you spot other mistakes of this nature, and want to try out making a PR, please feel free 😄
