### ISSUE TITLE
Line break and infix operators

### ISSUE THREAD

**Issue by lorenzwalthert** [tidyverse/style#45]
In [styler](https://github.com/krlmlr/styler/issues/255), we were wondering whether it would make sense to add a rule to the style guide that says
> If you use infix operators (such as `|`, `&` etc.) and you decide to break the line around them, the 
> line break should occur after the infix operator, not before it.
```r
# good
if (a_long_condition & and_another_long_condition &
  one_more) {
    # do something
}

# bad
if (a_long_condition & and_another_long_condition
  & one_more) {
    # do something
}
```

Or whether conditions should not be that long anyways so the problem does not occur and / or it is an edge case not worth mentioning.

In any case, we would probably implement a rule in styler that moves the infix operator one line up to change `# bad` above to `# good`.
cc: @krlmlr.

**Comment by hadley** [comment]
I don't think there's a good way to style that without rewriting.

**Comment by lorenzwalthert** [comment]
Ok, fine.
