### ISSUE TITLE
File naming conventions specific to packages

### ISSUE THREAD

**Issue by jennybc** [tidyverse/style#47]
Not sure if this belongs here or <http://r-pkgs.had.co.nz>

Naming files, e.g. if function is `foo_bar()` is the file `R/foo_bar.R` or `R/foo-bar.R`. Are you allowed to define `foo_yo()` in here too?

Relationship between name of file where a function is defined and the (name of) test file in which it is tested.

**Comment by hadley** [comment]
I think, in general, it should match the function name, i.e. `R/foo_bar.R`. But this has varied over time, so tidyverse packages are far from consistent.

Maybe we also need a tests chapter to mention the file names? Or should we divide the book into "scripts" vs "packages" and have file naming chapters in both?

**Comment by hadley** [comment]
Relationship between R file and test file is now documented, but I can't figure out where the general layout advice should go.
