### ISSUE TITLE
Code font for package names or not?

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [tidyverse/style#50]
I believe R4DS does not use `codefont` for package names. Instead uses bolding in the first mention and regular text later on. Is this the recommended way to format how package names appear in writing? It would be useful to make a recommendation about this at http://style.tidyverse.org/code-documentation.html#code-font.

**Comment by hadley** [comment]
We bold first use in books, blog posts etc, but that doesn't feel right for documentation.
