### ISSUE TITLE
Published site does not have master branch as source?

### ISSUE THREAD

**Issue by lorenzwalthert** [tidyverse/style#54]
How come I can see the chapter on error messages published under http://style.tidyverse.org/
although #53 is not yet merged into master?
http://style.tidyverse.org/error-messages.html

**Comment by hadley** [comment]
The problem is that I was thinking about this as a "custom deploy", and deployment doesn't happen in PRs. But I've actually used `after_success` which does. I'll try using a deployment "script" instead.

**Comment by hadley** [comment]
@juliasilge this probably affects tidy text too

**Comment by juliasilge** [comment]
Thanks for the heads up.
