### ISSUE TITLE
Add guidelines about empty lines?

### ISSUE THREAD

**Issue by martin-mfg** [tidyverse/style#65]
I couldn't find any advice in the style guide about empty lines. Maybe you want to add some information on that topic?
Questions that could be interesting in my opinion are for example:
- Is there a limit on the number of consecutive empty lines?
- Are there places where empty lines are considered necessary to improve readability?
- Are empty lines allowed inside multi-line function calls?

Regarding the third question, an example where empty lines inside a function call could be considered helpful is this:
```R
greetings_long <- c(

  paste0(
    "Welcome back ",
    name,
    "!"
  ),

  paste0(
    "Hello ",
    name,
    ". How are you?"
  ),

  paste0(
    "Aren't you ",
    name,
    "? Nice to meet you!"
  )

)
```

**Comment by hadley** [comment]
I don't think we need an explicit guideline on them. Use empty lines where it helps break code up into semantic chunks.
