### ISSUE TITLE
Pipes style

### ISSUE THREAD

**Issue by Yeedle** [tidyverse/style#7]
@hrbrmstr had some good pointers re pipes in his [RStudio::conf talk](https://www.rstudio.com/resources/videos/writing-readable-code-with-pipes/), e.g. don't use the pipe for just one function (`mtcars %>% str()`), piping data into ggplot is probably not a good idea (breaks the pipes should be 'atomic' rule, etc.

**Comment by hadley** [comment]
Those are already mostly there or I don't agree with them 😉
