### ISSUE TITLE
Encourage UTF-8 encoding

### ISSUE THREAD

**Issue by lorenzwalthert** [tidyverse/style#71]
The use of different file encodings is a root of headache for both package developers and end-users, hence, @krlmlr proposes to promote UTF-8 as *the* encoding to use. Is a paragraph on that welcomed in the tidyverse style guide?
Migrated from https://github.com/r-lib/styler/issues/376#issuecomment-376004826.

**Comment by krlmlr** [comment]
The downside is that Windows users won't be able to compile packages that contain UTF-8 codepoints that have no equivalent in their current locale, because `source()` uses the native encoding internally. Effectively this means that files should be ASCII-encoded for best portability.

**Comment by hadley** [comment]
I don't think it's needed here - usethis now creates by default, and it's mentioned elsewhere (e.g. by testthat).
