### ISSUE TITLE
Suggestion: comment style

### ISSUE THREAD

**Issue by prosoitos** [tidyverse/style#72]
Current tidyverse comment style:

`# ` for any comment

My suggestion:

`## ` for a full line comment
`# ` for a comment on a code line

Example:
```
## Example code
y <- 3 + 2          # I don't have imagination
```

Rationale:
- consistant with other style guides (e.g. https://www.bioconductor.org/developers/how-to/coding-style/)
- consistant with emacs comments
- allows auto-formatting options which indent and align single hashes, but do not indent double hashes (or indent them at the same level as surrounding code, depending on settings). This is very convenient!
- looks cleaner (this is so objective lol. I know :smile:)

Note: Jim Hester was ok to accept my PR to allow `## ` in `commented_code_linter` in the lintr package (see jimhester/lintr#301). So lintr is now happy with `## ` full line comments :grinning:

**Comment by hadley** [comment]
I don't see the need to distinguish full line from partial line comments.

**Comment by prosoitos** [comment]
Fair enough.
