### ISSUE TITLE
Function arguments prefixed with `.`

### ISSUE THREAD

**Issue by Torvaney** [tidyverse/style#75]
Initially raised in: https://community.rstudio.com/t/function-argument-naming-conventions-x/7764

In a lot of tidyverse packages, function arguments are prefixed with a `.`, for instance in purrr:

```r
purrr::map
#> function (.x, .f, ...) 
#> {
#>     .f <- as_mapper(.f, ...)
#>     .Call(map_impl, environment(), ".x", ".f", "list")
#> }
#> <environment: namespace:purrr>
```

As I understand it, this is to minimise ambiguity/clashes with other variable names in the current R session. Is this the preferred style for naming function arguments? Are there times when this isn't the preferred style?

Is it worth adding a note in the `functions` section clarifying this?

**Comment by hadley** [comment]
It is not a general principle. It's something that only apply to FP tools like purrr, because you don't want to confuse the arguments to `map()` with the arguments to `.f`
