### ISSUE TITLE
Define formatting for writing about `NAMESPACE` and `DESCRIPTION`

### ISSUE THREAD

**Issue by batpigandme** [tidyverse/style#92]
Should `NAMESPACE` and `DESCRIPTION` be surrounded by backticks when referenced in markdown?

Currently we're inconsistent. In the roxygen vignettes (e.g. [Package namespace](https://cran.r-project.org/web/packages/roxygen2/vignettes/namespace.html)) we use backticks, but we do so inconsistently in [NEWS](https://github.com/klutometis/roxygen/blob/master/NEWS.md#roxygen2-610) for same. 

This might fall under a broader umbrella, and I'm missing which one.

**Comment by batpigandme** [comment]
This PR would make `NAMESPACE` definitively "backticked" in roxygen NEWS https://github.com/klutometis/roxygen/pull/763.

**Comment by hadley** [comment]
Yes, we should I think.
