### ISSUE TITLE
Use pipe with assignment

### ISSUE THREAD

**Issue by echasnovski** [tidyverse/style#95]
In [Assignment](http://style.tidyverse.org/pipes.html#assignment-1) section of "Pipe" chapter there is a guideline "Use a separate line for the target of the assignment followed by `<-`.". However, I think it is not intuitive and used very rarely by community compared to placing source object after the `<-`. There are also [examples in R4DS](http://r4ds.had.co.nz/iteration.html#shortcuts) of this style.

Maybe it is better to change this?

**Comment by lorenzwalthert** [comment]
cc @krlmlr this is not implemented in styler currently.

**Comment by krlmlr** [comment]
I think we'd need to come to a conclusion in the style guide first before adapting _styler_. Would you mind filing an issue there?
